stages:
  - test
  - release

static code check:
  stage: test
  image: devdrops/staticcheck:latest
  script:
    - staticcheck $CI_PROJECT_DIR/cmd/
    - staticcheck $CI_PROJECT_DIR/pkg/exporter/
    - staticcheck $CI_PROJECT_DIR/pkg/config/
    - staticcheck $CI_PROJECT_DIR/pkg/web/
  allow_failure: true

release:
  image: node:18-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git
  script:
    - semantic-release
  only:
    - main
  except:
    changes:
      - "CHANGELOG.md"

# only builds on tag creation
build binary:
  image: golang:1.20
  stage: release
  script:
    - CGO_ENABLED=0 go mod download
    - CGO_ENABLED=0 go build -o pveinventory-$CI_COMMIT_TAG cmd/main.go
  only:
    - tags
  except:
    - branches
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - ./pveinventory-*
