FROM golang:1.20 AS build

WORKDIR /build

COPY . .

RUN CGO_ENABLED=0 go mod download

RUN CGO_ENABLED=0 go build -o pveinventory cmd/main.go

FROM scratch AS release

USER 10001
WORKDIR /app

COPY --from=build /build/pveinventory /app/pveinventory

ENTRYPOINT ["/app/pveinventory"]
CMD ["-f", "/app/MY_CONFIG.yaml"]